apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foo-microservice.fullname" . }}
  labels:
    {{- include "foo-microservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "foo-microservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "foo-microservice.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "foo-microservice.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "2000Mi"
              cpu: "2"