{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bar-microservice-ingress.fullname" . }}
  labels:
    {{- include "bar-microservice.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.hostPrefix }}.{{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "bar-microservice.fullname" . }}
            port:
              name: http
{{ end }}