name: Pull Request Cleanup
on:
  pull_request:
    types: [closed]

jobs:
  cleanup-pr:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Docker - Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 'Docker - Cleanup PR Tags'
      run: |
        docker rmi $(docker images --filter=reference="foo-microservice:pr-${{ github.event.pull_request.number }}" -q)
        docker rmi $(docker images --filter=reference="bar-microservice:pr-${{ github.event.pull_request.number }}" -q)
        