name: Microservice Pull Request

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main

jobs:
  path-filters:
    runs-on: ubuntu-latest
    outputs:
      frontend-modified: ${{ steps.filter.outputs.gateway }}
      bar-modified: ${{ steps.filter.outputs.bar }}
      foo-modified: ${{ steps.filter.outputs.foo }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          gateway:
            - 'Gateway/**'
          bar:
            - 'Bar/**'
          foo:
            - 'Foo/**'

  frontend-gateway:
    needs: path-filters
    if: needs.path-filters.outputs.frontend-modified == 'true'
    concurrency: 
      group: gateway-pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    uses: ./.github/workflows/pull-request-workflow.yml
    secrets: inherit
    with:
      service-name: 'gateway'
      solution-directory: './Bridge2Kubernetes.sln'
      docker-file-path: 'Gateway/FrontendGateway/Dockerfile'
      repository: 'docker.io/spencerritzow/frontend-gateway'

  bar-microservice:
    needs: path-filters
    if: needs.path-filters.outputs.bar-modified == 'true'
    concurrency: 
      group: bar-pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    uses: ./.github/workflows/pull-request-workflow.yml
    secrets: inherit
    with:
      service-name: 'services-bar'
      solution-directory: './Bridge2Kubernetes.sln'
      docker-file-path: 'Bar/BarMicroservice/Dockerfile'
      repository: 'docker.io/spencerritzow/bar-microservice'

  foo-microservice:
    needs: path-filters
    if: needs.path-filters.outputs.foo-modified == 'true'
    concurrency: 
      group: foo-pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    uses: ./.github/workflows/pull-request-workflow.yml
    secrets: inherit
    with:
      service-name: 'services-foo'
      solution-directory: './Bridge2Kubernetes.sln'
      docker-file-path: 'Foo/FooMicroservice/Dockerfile'
      repository: 'docker.io/spencerritzow/foo-microservice'
      